run-name: e2e - ${{ github.event.deployment.environment }}

on:
  deployment_status:
jobs:
  run-e2es:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install dependencies
        run: pnpm i && npx playwright install --with-deps
      - name: Run tests
        run: pnpm e2e
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
          E2E_WALLET_ENDPOINT: ${{ secrets.E2E_WALLET_ENDPOINT }}
          E2E_ODOO_USERNAME: ${{ secrets.E2E_ODOO_USERNAME }}
          E2E_ODOO_PASSWORD: ${{ secrets.E2E_ODOO_PASSWORD }}
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1
